farm_map_openweathermap.settings:
  type: config_object
  label: 'OpenWeatherMap Settings'
  mapping:
    api_key:
      type: string
      label: 'OpenWeatherMap API Key'
      description: 'The API key used to request OpenWeatherMap imagery layers.'
